config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :jobs do
      member do
        post :publish
        post :hide
      end
      resources :resumes
    end
  end

  resources :jobs do
    collection do
      get :search
    end
      resources :resumes
  end

    root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord

  validates :title, presence: true
  validates :wage_upper_bound, presence: true
  validates :wage_lower_bound, presence: true
  validates :wage_lower_bound, numericality: { greater_than: 0}
  scope :published, -> { where(is_hidden: false) }
  scope :recent, -> { order("created_at DESC") }
  has_many :resumes

  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end

end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user
  belongs_to :job

  mount_uploader :attachment, AttachmentUploader

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :resumes

  def admin?
    is_admin
  end


end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :require_is_admin
  layout "admin"

  def show
    @job = Job.find(params[:id])
  end

  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])

    @job.destroy

    redirect_to admin_jobs_path
  end

  def publish
    @job = Job.find(params[:id])
    @job.publish!

    redirect_to :back
  end

  def hide
    @job = Job.find(params[:id])
    @job.hide!

    redirect_to :back
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden)
  end


  def require_is_admin
     if !current_user.admin?
       flash[:alert] = 'You are not admin'
       redirect_to root_path
     end
  end
  
end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin

  layout 'admin'

  def index
    @job = Job.find(params[:job_id])
    @resumes = @job.resumes.order('created_at DESC')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def require_is_admin
    if !current_user.admin?
      flash[:alert] = 'You are not admin'
      redirect_to root_path
    end
  end
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
  before_action :validate_search_key, only: [:search]
  def show
    @job = Job.find(params[:id])
    if @job.is_hidden
      flash[:warning] = "This Job already archived"
      redirect_to root_path
    end
  end


  def index
    @jobs = case params[:order]
            when 'by_lower_bound'
              Job.published.order('wage_lower_bound DESC')
            when 'by_upper_bound'
              Job.published.order('wage_upper_bound DESC')
            else
              Job.published.recent
            end

  end


  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path
  end

  def search
    if @query_string.present?
      search_result = Job.published.ransack(@search_criteria).result(:distinct => true)
      @jobs = search_result.recent.paginate(:page => params[:page], :per_page => 5)
    end
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden, :city, :company, :category)
  end

  protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "")
    if params[:q].present?
    @search_criteria = {
      title_or_company_or_city_cont: @query_string
    }
    end
  end


  def search_criteria(query_string)
    { :title_cont => query_string }
  end


end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!
  

  def new
    @job = Job.find(params[:job_id])
    @resume = Resume.new
  end

  def create
    @job = Job.find(params[:job_id])
    @resume = Resume.new(resume_params)
    @resume.job = @job
    @resume.user = current_user

    if @resume.save
      flash[:notice] = "成功提交简历"
      redirect_to job_path(@job)
    else
      render :new
    end
  end

  private

  def resume_params
    params.require(:resume).permit(:content, :attachment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
        @q = Job.ransack(params[:q])
  end

end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/admin/resumes_helper.rb
module Admin::ResumesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
      @resource ||= User.new
  end

  def resource_class
      User
  end

  def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/jobs_helper.rb
module JobsHelper

  def render_job_status(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end
  
  def render_highlight_content(job,query_string)
    excerpt_cont = excerpt(job.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/jobs/edit.html.erb
<h1> Edit a job </h1>

<%= simple_form_for [:admin, @job ] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
<% end %>

app/views/admin/jobs/index.html.erb
<div class="pull-right">
  <%= link_to new_admin_job_path, class: "btn btn-default btn-lg" do %><i class="glyphicon glyphicon-open"></i>add a job <% end %>

</div>

<br><br>

<table class="table table-boldered table-striped custab" >
  <thead>
        <tr>
            <td>
                职缺
            </td>

            <td>
              收到履历数量
            </td>
            <td>
                薪资下限
            </td>
            <td>
                薪资上限
            </td>
            <td>
                管理选项
            </td>
            <td>
                刊登时间
            </td>
        </tr>
    </thead>

    <% @jobs.each do |job| %>
    <tr>
    <td>
      <%= render_job_status(job) %>
      <%= link_to(job.title, admin_jobs_path(job)) %>
    </td>

    <td> <%= link_to(job.resumes.count, admin_job_resumes_path(job)) %> </td>
    <td> <%= job.wage_lower_bound %> </td>
    <td> <%= job.wage_upper_bound %> </td>
    <td>
      <%= link_to edit_admin_job_path(job), class: "btn btn-xs btn-info" do %><i class="fa fa-pencil"></i><% end %>
      <%= link_to admin_job_path(job), :method => :delete, :class => "btn btn-xs  btn-danger", :data => { :confirm => "Are you sure?" } do %><i class="fa fa-trash-o"></i><% end %>
      <% if job.is_hidden %>
      <%= link_to publish_admin_job_path(job) , :method => :post, :class => "btn btn-xs btn-success" do %><i class="fa fa-eye"></i><% end %>
      <% else %>
      <%= link_to hide_admin_job_path(job), :method => :post,  :class => "btn btn-xs btn-warning" do %><i class="fa fa-eye-slash"></i><% end %>
      <% end %>
    </td>

    <td>
        <%= job.created_at %>
    </td>
    </tr>
    <% end %>
  </table>

app/views/admin/jobs/new.html.erb
<h1> Add a job </h1>

<%= simple_form_for [:admin,@job] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>
<%= f.submit "Submit" %>
  
<% end %>

app/views/admin/resumes/_resume.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-md-12">
        <h3 class="panel-title">
          <%= resume.user.email %>
        </h3>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="trix-content">
       <p> <%= simple_format(resume.content) %> </P>
    </div>

      <hr>

      <% if resume.attachment.present? %>
        <i class="fa fa-paperclip"> </i>
        <%= link_to("Download Resume", resume.attachment_url) %>
      <% else %>
         No Attachment
      <% end %>
    </div>

</div>

app/views/admin/resumes/index.html.erb
<h2> <%= @job.title %> - 履历列表</h2>

<hr>
<%=render :partial => "resume", :collection => @resumes, :as => :resume %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
  <footer>
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <div class="text-center">
              Copyright ©2017 优趣实习
               <br>Design by Yan Xiaoyu
          </div>
        </div>
      </div>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/"><img src='<%= image_url 'logo.png' %>' >优趣实习</a>
        </div>
        <ul class="nav navbar-nav">
          <li>
            <div class="form-group form-inline search-bar">
              <%= render :partial => "jobs/search_bar" %>
            </div>
          </li>
        </ul>
        <!-- <form class="navbar-form navbar-right" action="/jobs/search" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="✓">
          <div class="input-group search-box">
            <input type="text" class="form-control" name="keyword" placeholder="优趣搜搜" value="">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <i class="fa fa-search"></i>
              </button>
            </div>
          </div>
        </form> -->
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
              <li><a href="#" data-toggle="modal" data-target="#signup-modal">注册</a></li>
              <li><a href="#" data-toggle="modal" data-target="#login-modal">登入</a></li>
                 <% else %>
                   <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                         Hi!, <%= current_user.email %>
                         <b class="caret"></b>
                     </a>
                     <ul class="dropdown-menu">
                         <% if current_user.admin? %>
                         <li> <%= link_to("Admin Panel", admin_jobs_path) %> </li>
                         <% end %>
                         <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                     </ul>
                   </li>
                 <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

<!-- 以下代码添加在最后 -->
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog" role="document">
    <div class="loginmodal-container">
       <h2>Log in</h2>
       <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
         <div class="form-inputs">
           <%= f.input :email, required: false, autofocus: true %>
           <%= f.input :password, required: false %>
           <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
         </div>
         <div class="form-actions">
           <%= f.button :submit, "Log in" %>
         </div>
       <% end %>
    </div>
  </div>
</div>


<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="loginmodal-container">
      <h2>Sign up</h2>
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :email, required: true, autofocus: true %>
          <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
          <%= f.input :password_confirmation, required: true %>
        </div>
        <div class="form-actions">
            <%= f.button :submit, "Sign up" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/_jobs_item.html.erb
<div class="row jobs-show">
  <div class="col-md-12 col-lg-10 col-lg-offset-1">
    <div class="pull-right">
      <% if user_signed_in? && !current_user.admin? %>
        <% if current_user && current_user.has_applied?(job) %>
          <%= link_to("Has Applied", new_job_resume_path(job), class: "btn btn-info btn-sm disabled", method: :get) %>
        <% else %>
          <%= link_to("Quick Apply", new_job_resume_path(job), class: "btn btn-info btn-sm", method: :get) %>
        <% end%>
      <% else %>
        <%= link_to("Quick Apply", new_job_resume_path(job), class: "btn btn-info btn-sm", method: :get) %>
      <% end %>
    </div>
    <p><%= link_to(job.title, job_path(job)) %></p>


    <div class="row">
      <div class="col-md-6">
        <p>Salary: <%= job.wage_lower_bound %> ~ <%= job.wage_upper_bound %> </p>
      </div>
      <div class="col-md-6">
        <p><i class="fa fa-address-card-o" aria-hidden="true"></i>  <%= job.category %></p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3 col-sm-6">
        <span><i class="fa fa-user-circle-o" aria-hidden="true"></i>  <%= job.company %></span>
      </div>
      <div class="col-md-3 col-sm-6">
        <span><i class="fa fa-location-arrow" aria-hidden="true"></i>  <%= job.city %></span>
      </div>
      <div class="col-md-3 col-sm-6">
        <span><i class="fa fa-clock-o" aria-hidden="true"></i>  <%= time_ago_in_words(job.created_at) %> ago</span>
      </div>
      <div class="col-md-3 col-sm-6">
        <span><i class="fa fa-envelope" aria-hidden="true"></i>  <%= job.contact_email %></span>
      </div>
    </div>
  </div>
</div>

app/views/jobs/_search_bar.html.erb
<div class="row">
  <div class="col-sm-9 col-lg-8 col-lg-offset-2">
    <%= form_tag search_jobs_path , :method => :get, :class => "jobs-search-form" do %>
      <div class="input-group">
        <input type="text" class="form-control search-bar-input" name="q" value="<%= params[:q] %>" placeholder="优趣搜">

        <span class="input-group-btn">
          <button type="submit" class="btn btn-default search-bar-submit">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div>
    <% end %>
  </div>
</div>

app/views/jobs/edit.html.erb
<h1> Edit a job </h1>

<%= simple_form_for @job do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
  
<% end %>

app/views/jobs/index.html.erb
<div class="col-md-8 col-centered">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>
      实习岗位
      <div class="pull-right">
         <%= link_to("Add a job", new_job_path, :class => "btn btn-default" ) %>
       </div>
       <div class="dropdown clearfix pull-right">
           <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
             排序
             <span class="caret"></span>
           </button>
           <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
             <li>
               <%= link_to("按照薪资下限排序", jobs_path(:order => "by_lower_bound")) %>
             </li>
             <li>
               <%= link_to("按照薪资上限排序", jobs_path(:order => "by_upper_bound")) %>
             </li>
             <li>
               <%= link_to("按照发表时间排序", jobs_path )%>
             </li>
           </ul>
         </div>
     </h3>

    <div class="panel-body">
      <table class="table table-boldered">
          <thead>
            <tr>
              <td>职缺</td>
              <td>薪资下限</td>
              <td>薪资上限</td>
              <td>刊登时间</td>
            </tr>
          </thead>
          <tbody>
            <% @jobs.each do |job| %>
            <tr>
              <td>
                <%= link_to(job.title, job_path(job)) %>
              </td>
              <td>
                <%= job.wage_lower_bound %>
              </td>
              <td>
                <%= job.wage_upper_bound %>
              </td>
              <td>
                <%= job.created_at %>
              </td>
            </tr>
            <% end %>
          </tbody>
      </table>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<h1> Add a job </h1>

<%= simple_form_for @job do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>
<%= f.submit "Submit" %>

<% end %>

app/views/jobs/search.html.erb
<div id="search-page" class="container-fluid jobs-show-page">
  <div class="col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
    <br>
    <div class="pull-right">
      <%= link_to(content_tag(:i, " Check All Jobs", class: "fa fa-reply-all"), jobs_path) %> |
      <%= link_to(content_tag(:i, " Back", class: "fa fa-arrow-left"), url_for(:back)) %>
    </div>

    <% if @jobs.blank?%>
      <br>
      <div>
        Opps! No any results matched, please try again.
      </div>
    <% else %>
      <h3>Total find <%= @jobs.count %> jobs</h3>
      <div class="divider"></div>
      <%= render :partial => "jobs_item", :collection => @jobs, :as => :job %>
      <div class="text-center">
        <%= will_paginate @jobs, renderer: BootstrapPagination::Rails %>
      </div>
    <% end %>
  </div>
</div>

app/views/jobs/show.html.erb
<h1> <%= @job.title %> </h1>

<p>
  <%= simple_format(@job.description) %>

</p>

<div class="text-center">
  <%= link_to("投递简历", new_job_resume_path(@job), :style => "front-size: 30px; text-decoration: underline;") %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
    <head>
         <title>Job Listing </title>
         <%= csrf_meta_tags %>

         <%= stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track': 'reload' %>
         <%= javascript_include_tag 'application', 'data-turbolinks-track': 'Reload' %>
    </head>

    <body>
         <div class="content">
          <div class="container-fluid">
            <div class="row">
              <%= render "common/navbar" %>  
            </div>
            <%= render "common/flashes" %>
              <div class="row">
                <ul class="nav nav-pills nav-stacked" style="max-width:100px; padding-top:20px;">
                  <li class="active"><%= link_to("Jobs", admin_jobs_path ) %> </li>
                </ul>

                                <div class="col-md-10">
                                     <%= yield %>
                                </div>
             </div>
          </div>
        </div>

        <%= render "common/footer" %>

    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>优趣实习</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="shortcut icon" href="/images/favicon.ico">
  </head>

  <body>

    <div class="container-fluid wrapper">
      <div class="row header">
          <%= render "common/flashes" %>
          <%= render "common/navbar" %>
      </div>

      <div class="row content">
        <%= yield %>
      </div>

      <div class="row footer">
        <%= render "common/footer" %>
      </div>
   </div>


  </body>
</html>

app/views/resumes/new.html.erb
<h3> 投递简历到 <%= @job.title %> </h3>
<hr>
<%= simple_form_for [@job, @resume] do |f| %>
  <%= f.input :content %>
  <%= f.input :attachment %>
  <%= f.submit "送出" %>
<% end %>